### PR TITLE
Create .github/workflows to configure Github CI

### PR DESCRIPTION
**Pull request by acmcarther**
This is just https://help.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-maven#starting-with-a-maven-workflow-template copied.

I was going to use Travis CI, but someone in hosts chat suggested this and it looks easy enough.

I'm not sure if this works, I'll be testing that out. 

---

The only thing that is required to enable this functionality is to include this new file in the project (in the correct directory). No configuration under repo Settings or repo Actions is necessary.

---

cc @jalexanderqed @apluscs @GrantComm @meagancheese

### CODE REVIEW

**Comment by acmcarther** [comment]
Oops I messed up

Need to move the file.

**Comment by acmcarther** [comment]
Nice, looks like it's running!

**Comment by acmcarther** [comment]
https://github.com/googleinterns/InterviewMe/pull/42/checks?check_run_id=823567409

**Comment by acmcarther** [comment]
I'll probably follow up on this PR with a change that updates the mvn statements to...

```
$ mvn -B verify --file pom.xml   
$ mvn -B test --file pom.xml   
```

... so that we run the tests.

(but those can be separate)

**Comment by acmcarther** [comment]
Well, the review of this is taking a while (which I guess is Karma in action). I'll make the verify+test change in this PR then.

**Review by jalexanderqed — APPROVED** [review]

**Review by GrantComm — APPROVED** [review]

**Pull request merged**
